export default {
  value: [
    {
      id: 20,
      tipoEvento: 'ACTUALIZACION PROGRAMADA',
      imagen:
        "<img src='../img/evento/program_updt.gif' Alt='Actualizacion Programada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1385689',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 21,
      tipoEvento: 'SIN CONTACTO',
      imagen: "<img src='../img/evento/ign_off.gif' Alt='Sin Contacto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386429',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 22,
      tipoEvento: 'CON CONTACTO',
      imagen: "<img src='../img/evento/ign_on.gif' Alt='Con Contacto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386457',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 23,
      tipoEvento: 'ALIMENTACION BATERIA',
      imagen:
        "<img src='../img/evento/feed_batery.gif' Alt='Alimentacion Bateria'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386461',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 24,
      tipoEvento: 'ENTRADA A GEOCERCA',
      imagen:
        "<img src='../img/evento/in_geofence.gif' Alt='Entrada a Geocerca'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386469',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 25,
      tipoEvento: 'SALIDA A GEOCERCA',
      imagen:
        "<img src='../img/evento/out_geofence.gif' Alt='Salida a Geocerca'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386477',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 26,
      tipoEvento: 'PUERTO DIGITAL AUXILIAR INACTIVO',
      imagen:
        "<img src='../img/evento/door_open.gif' Alt='Puerto Digital Auxiliar Inactivo'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386481',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 27,
      tipoEvento: 'DATOS SERIALES AUXILIARES',
      imagen:
        "<img src='../img/evento/mdt_event.gif' Alt='Datos seriales auxiliares'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386485',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 28,
      tipoEvento: 'EVENTO DE CONDUCTOR',
      imagen: "<img src='../img/evento/spacer.gif' Alt=''>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386488',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 29,
      tipoEvento: 'PUERTO DIGITAL AUXILIAR ACTIVO',
      imagen:
        "<img src='../img/evento/door_close.gif' Alt='Puerto Digital Auxiliar Activo'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386492',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 30,
      tipoEvento: 'ESTACIONARIO',
      imagen:
        "<img src='../img/evento/stationary_alert.gif' Alt='Sin movimiento'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386516',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 31,
      tipoEvento: 'RESPUESTA A UNA CONSULTA',
      imagen:
        "<img src='../img/evento/query.gif' Alt='Respuesta a una Consulta'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386524',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 32,
      tipoEvento: 'MOVIMIENTO CON ENCENDIDO SIN CONTACTO',
      imagen:
        "<img src='../img/evento/vhcl_moved.gif' Alt='Movimiento con Encendido Sin Contacto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386528',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 33,
      tipoEvento: 'ANTENA GPS DESCONECTADA',
      imagen:
        "<img src='../img/evento/Disconnected.gif' Alt='Antena GPS Desconectada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386532',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 34,
      tipoEvento: 'MDT FUERA DE LINEA',
      imagen:
        "<img src='../img/evento/mdt_offline.gif' Alt='MDT Fuera de Linea'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386532',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 35,
      tipoEvento: 'ANTENA GPS CONECTADA',
      imagen:
        "<img src='../img/evento/Connected.gif' Alt='Antena GPS Conectada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386536',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 36,
      tipoEvento: 'MOVIMIENTO NO AUTORIZADO',
      imagen:
        "<img src='../img/evento/vhcl_noauth.gif' Alt='Movimiento No Autorizado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138654',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 37,
      tipoEvento: 'MDT EN LINEA',
      imagen: "<img src='../img/evento/mdt_online.gif' Alt='MDT en Linea'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386544',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 38,
      tipoEvento: 'EVENTO EMS',
      imagen: "<img src='../img/evento/ems_event.gif' Alt='Evento EMS'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386548',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 39,
      tipoEvento: 'NUEVO MDT CONECTADO',
      imagen:
        "<img src='../img/evento/mdt_event.gif' Alt='Nuevo MDT conectado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386548',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 40,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386552',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 41,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386555',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 42,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386559',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 43,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386559',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 44,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386563',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 45,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386567',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 46,
      tipoEvento: 'UNIDAD CONECTADA',
      imagen:
        "<img src='../img/evento/unit_Connected.gif' Alt='Unidad conectada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386571',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 47,
      tipoEvento: 'UNIDAD DESCONECTADA',
      imagen:
        "<img src='../img/evento/unit_Disconnected.gif' Alt='Unidad desconectada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386571',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 48,
      tipoEvento: 'S.O.S.',
      imagen:
        "<img src='../img/evento/illegal_movement_alert.gif' Alt='S.O.S.'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386575',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 49,
      tipoEvento: 'SENSOR MOVIMIENTO',
      imagen:
        "<img src='../img/evento/unauthorised_alert.gif' Alt='Sensor de movimiento'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386579',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 50,
      tipoEvento: 'ALIMENTACION BATERIA DESCONECTADA',
      imagen:
        "<img src='../img/evento/feed_batery.gif' Alt='Alimentacion Bateria'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386583',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 56,
      tipoEvento: 'INICIO DE SESION',
      imagen: "<img src='../img/evento/unit_Connected.gif' Alt='Sin Contacto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386583',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 57,
      tipoEvento: 'FIN DE SESION',
      imagen:
        "<img src='../img/evento/unit_Disconnected.gif' Alt='Con Contacto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386587',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 58,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386591',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 59,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386595',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 60,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386599',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 61,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386599',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 62,
      tipoEvento: 'EXCESO DE VELOCIDAD',
      imagen:
        "<img src='../img/evento/overspeed.gif' Alt='Exceso de velocidad'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386603',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 63,
      tipoEvento: 'APERTURA DE PUERTA',
      imagen:
        "<img src='../img/evento/door_open.png' Alt='Apertura de puerta'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386607',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 64,
      tipoEvento: 'CIERRE DE PUERTA',
      imagen: "<img src='../img/evento/door.png' Alt='Apertura de puerta'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386607',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 65,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386611',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 66,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386615',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 67,
      tipoEvento: 'CARGA DE BATERIA INTERNA COMPLETADA',
      imagen:
        "<img src='../img/evento/carga_bateria_interna_ok.gif' Alt='Carga de batería interna completada'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386618',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 68,
      tipoEvento: 'EMS: PRESION DE ACEITE',
      imagen:
        "<img src='../img/evento/ems_presion_aceite.gif' Alt='EMS Presión de aceite'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386618',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 69,
      tipoEvento: 'EMS: INICIO EXCESO DE RPM',
      imagen:
        "<img src='../img/evento/ems_inicio_exceso_rpm.gif' Alt='EMS Inicio Exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386622',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 70,
      tipoEvento: 'EMS: FIN EXCESO DE RPM',
      imagen:
        "<img src='../img/evento/ems_fin_exceso_rpm.gif' Alt='EMS Fin Exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386626',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 71,
      tipoEvento: 'CARGANDO BATERIA INTERNA',
      imagen:
        "<img src='../img/evento/feed_batery.png' Alt='Cargando batería interna'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386626',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 72,
      tipoEvento: 'DESCONOCIDO',
      imagen: "<img src='../img/evento/desconocido.gif' Alt='Desconocido'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138663',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 73,
      tipoEvento: 'EMS: FRENADO BRUSCO',
      imagen:
        "<img src='../img/evento/ems_frenado_brusco.gif' Alt='EMS Frenado brusco'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386634',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 74,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386638',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 75,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386638',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 76,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386642',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 77,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386646',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 78,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138665',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 79,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138665',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 80,
      tipoEvento: 'DESCONEXION MANUAL',
      imagen:
        "<img src='../img/evento/driver_off.gif' Alt='Desconexión manual'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386654',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 81,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386658',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 82,
      tipoEvento: 'CONDUCTOR DESCONOCIDO',
      imagen:
        "<img src='../img/evento/unknown.gif' Alt='Conductor desconocido'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386662',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 83,
      tipoEvento: 'CONEXION OK',
      imagen: "<img src='../img/evento/driver_on.gif' Alt='Conexión OK'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386662',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 84,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386666',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 85,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138667',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 86,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386674',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 87,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386674',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 88,
      tipoEvento: 'CINTURON DE SEGURIDAD CERRADO',
      imagen:
        "<img src='../img/evento/seatbeltClosed.gif' Alt='Cinturón de seguridad cerrado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386678',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 89,
      tipoEvento: 'CINTURON DE SEGURIDAD ABIERTO',
      imagen:
        "<img src='../img/evento/seatbeltOpen.gif' Alt='Cinturón de seguridad abierto'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386681',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 90,
      tipoEvento: 'FRENO DE MANO ACCIONADO',
      imagen:
        "<img src='../img/evento/frenomano1.jpg' Alt='Freno de mano accionado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386685',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 91,
      tipoEvento: 'FRENO DE MANO LIBERADO',
      imagen:
        "<img src='../img/evento/frenomano2.jpg' Alt='Freno de mano liberado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386685',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 92,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386689',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 93,
      tipoEvento: 'SQUARELL: EXCESO DE VELOCIDAD',
      imagen:
        "<img src='../img/squarell/speedstart.png' Alt='Inicio de exceso de velocidad'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386693',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 94,
      tipoEvento: 'SQUARELL: FIN EXCESO DE VELOCIDAD',
      imagen:
        "<img src='../img/squarell/speedstop.png' Alt='Fin de exceso de velocidad'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386693',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 95,
      tipoEvento: 'SQUARELL: EXCESO DE RPM',
      imagen:
        "<img src='../img/squarell/rpmstart.png' Alt='Inicio de exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386697',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 96,
      tipoEvento: 'SQUARELL: FIN EXCESO DE RPM',
      imagen:
        "<img src='../img/squarell/rpmstop.png' Alt='Fin de exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386701',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 97,
      tipoEvento: 'SQUARELL: EXCESO TEMPERATURA',
      imagen:
        "<img src='../img/squarell/tempstart.png' Alt='Inicio de exceso de temperatura'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386701',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 98,
      tipoEvento: 'SQUARELL: FIN EXCESO TEMPERATURA',
      imagen:
        "<img src='../img/squarell/tempstop.png' Alt='Fin de exceso de temperatura'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386705',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 99,
      tipoEvento: 'SQUARELL: EXCESO DE ACELERACION',
      imagen:
        "<img src='../img/squarell/acceleration.png' Alt='Exceso de aceleración'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386709',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 100,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386713',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 101,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386713',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 102,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386717',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 103,
      tipoEvento: 'SQUARELL: FRENADO BRUSCO',
      imagen: "<img src='../img/squarell/brake.png' Alt='Frenado brusco'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386721',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 104,
      tipoEvento: 'SQUARELL: CHOQUE',
      imagen: "<img src='../img/squarell/incident.png' Alt='Choque'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386725',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 105,
      tipoEvento: 'SQUARELL: EXCESO DE RALENTI',
      imagen:
        "<img src='../img/squarell/incident.png' Alt='Exceso de ralenti'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386725',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 106,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386729',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 107,
      tipoEvento: 'SQUARELL: INICIO DE VIAJE',
      imagen:
        "<img src='../img/squarell/EMSViajeIni.png' Alt='Inicio de viaje (EMS)'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386733',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 108,
      tipoEvento: 'SQUARELL: TERMINO DE VIAJE',
      imagen:
        "<img src='../img/squarell/EMSViajeFin.png' Alt='Fin de viaje (EMS)'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386733',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 109,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386737',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 110,
      tipoEvento: 'CONDUCCION AGRESIVA',
      imagen:
        "<img src='../img/evento/ConduccionAgresiva.png' Alt='Conducción agresiva'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386741',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 111,
      tipoEvento: 'CHOQUE',
      imagen: "<img src='../img/squarell/incident.png' Alt='Choque'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386745',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 112,
      tipoEvento: 'EXCESO DE VELOCIDAD 2',
      imagen:
        "<img src='../img/evento/overspeed.gif' Alt='Exceso de velocidad *'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386745',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 113,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386748',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 114,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386768',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 115,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386772',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 116,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386772',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 117,
      tipoEvento: '',
      imagen: '',
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386776',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 118,
      tipoEvento: 'CONEXION ERROR',
      imagen:
        "<img src='../img/evento/unknown.gif' Alt='Conductor desconocido'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.138678',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 119,
      tipoEvento: 'SQUARELL: EXCESO DE VELOCIDAD',
      imagen:
        "<img src='../img/squarell/speedstart.png' Alt='Inicio de exceso de velocidad'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386784',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 120,
      tipoEvento: 'SQUARELL: FIN EXCESO DE VELOCIDAD',
      imagen:
        "<img src='../img/squarell/speedstop.png' Alt='Fin de exceso de velocidad'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386784',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 121,
      tipoEvento: 'SQUARELL: EXCESO DE RPM',
      imagen:
        "<img src='../img/squarell/rpmstart.png' Alt='Inicio de exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386788',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 122,
      tipoEvento: 'SQUARELL: FIN EXCESO DE RPM',
      imagen:
        "<img src='../img/squarell/rpmstop.png' Alt='Fin de exceso de RPM'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386792',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 123,
      tipoEvento: 'SQUARELL: EXCESO TEMPERATURA',
      imagen:
        "<img src='../img/squarell/tempstart.png' Alt='Inicio de exceso de temperatura'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386808',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 124,
      tipoEvento: 'SQUARELL: FIN EXCESO TEMPERATURA',
      imagen:
        "<img src='../img/squarell/tempstop.png' Alt='Fin de exceso de temperatura'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386811',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 125,
      tipoEvento: 'SQUARELL: EXCESO DE ACELERACION',
      imagen:
        "<img src='../img/squarell/acceleration.png' Alt='Exceso de aceleración'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386815',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 126,
      tipoEvento: 'SQUARELL: FRENADO BRUSCO',
      imagen: "<img src='../img/squarell/brake.png' Alt='Frenado brusco'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386815',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 127,
      tipoEvento: 'SQUARELL: CHOQUE',
      imagen: "<img src='../img/squarell/incident.png' Alt='Choque'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386819',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 128,
      tipoEvento: 'SQUARELL: EXCESO DE RALENTI',
      imagen:
        "<img src='../img/squarell/incident.png' Alt='Exceso de ralenti'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386823',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 129,
      tipoEvento: 'SQUARELL: INICIO DE VIAJE',
      imagen:
        "<img src='../img/squarell/EMSViajeIni.png' Alt='Inicio de viaje (EMS)'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386827',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 130,
      tipoEvento: 'SQUARELL: TERMINO DE VIAJE',
      imagen:
        "<img src='../img/squarell/EMSViajeFin.png' Alt='Fin de viaje (EMS)'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386827',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 131,
      tipoEvento: 'CONDUCCION AGRESIVA',
      imagen:
        "<img src='../img/evento/ConduccionAgresiva.png' Alt='Conducción agresiva'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386831',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 132,
      tipoEvento: 'CHOQUE',
      imagen: "<img src='../img/squarell/incident.png' Alt='Choque'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386835',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 133,
      tipoEvento: 'EXCESO DE VELOCIDAD 2',
      imagen:
        "<img src='../img/evento/overspeed.gif' Alt='Exceso de velocidad *'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386835',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 134,
      tipoEvento: 'EVENTO MDT',
      imagen:
        "<img src='../img/evento/mdt_event.gif' Alt='Nuevo MDT conectado'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386839',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 135,
      tipoEvento: 'APERTURA DE PUERTA',
      imagen:
        "<img src='../img/evento/door_open.png' Alt='Apertura de puerta'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386843',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 136,
      tipoEvento: 'CIERRE DE PUERTA',
      imagen: "<img src='../img/evento/door.png' Alt='Apertura de puerta'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386847',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 137,
      tipoEvento: 'CARGANDO',
      imagen: "<img src='../img/evento/frigo_on.gif' Alt='Cargando'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386847',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 138,
      tipoEvento: 'DESCARGANDO',
      imagen: "<img src='../img/evento/frigo_off.gif' Alt='Descargando'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386851',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 139,
      tipoEvento: 'PULSADOR EVENTO ON',
      imagen: "<img src='../img/evento/buttonON.png' Alt='Pulsador ON'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386855',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 140,
      tipoEvento: 'PULSADOR EVENTO OFF',
      imagen: "<img src='../img/evento/buttonOFF.png' Alt='Pulsador OFF'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386855',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
    {
      id: 150,
      tipoEvento: 'BATERIA DESCARGANDOSE',
      imagen:
        "<img src='../img/evento/batery_low.gif' Alt='Bateria Descargandose'>",
      usuarioCreadorId: 1,
      fechaCreacion: '2020-02-12T19:51:12.1386859',
      usuarioModificacionId: null,
      fechaModificacion: null,
      actividades: null,
      descargaActividadTipo: null,
    },
  ],
  formatters: [],
  contentTypes: [],
  declaredType: null,
  statusCode: 200,
};
