export interface FlotaVehiculoInterface {
  cod_vehiculo: string; // "211772",
  cod_flota: string; // "9763",
  nom_flota: string; // "Pascual Pizarro",
  patente_vehiculo: string; // "LHPZ70",

  // Not necessary yet.
  // id: string;// "88435",
  // mandante: string;// "rut_8939752",
  // esquema_bd: string;// "'rut_8939752'",
  // qanalytics: string;// "NO",
  // motores_qanalytics: string;// [],
  // insert_auto: string;// "PN",
  // wisetrack_insertarposicion: string;// "NO",
  // activo: string;// "t",
  // cmp_btrack: string;// "NO",
  // fecha_ingreso: string;// "2022-05-02 17:36:26.677344",
  // fecha_desactivacion: string;// "",
  // jdata: string;// "",
  // heligrafics: string;// "NO",
  // owl: string;// "NO",
  // avl_chile: string;// "NO",
  // beetrack: string;// "NO",
  // log_solutions: string;// "NO",
  // rut_cliente: string;// "'8939752'",
  // samtech_dch: string;// "NO",
  // avl: string;// "NAVMAN",
  // int_codelco: string;// "NO",
  // int_samtech_cim: string;// "NO",
  // estado_cuadre: string;// "OK"
}
