export default [
  {
    id: 1,
    padreId: 0,
    clienteId: 1,
    responsableFlotaId: 4,
    responsableMantenimientoFlotaId: 4,
    nombre: 'Flota Base',
    descripcion: 'Flota Base',
    estado: 3,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 11,
    padreId: 0,
    clienteId: 2,
    responsableFlotaId: 4,
    responsableMantenimientoFlotaId: 4,
    nombre: 'Flota Base',
    descripcion: 'Flota Base',
    estado: 3,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 14,
    padreId: 0,
    clienteId: 2,
    responsableFlotaId: 4,
    responsableMantenimientoFlotaId: 4,
    nombre: 'Flota Sur',
    descripcion: 'Flota Sur',
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 21,
    padreId: 0,
    clienteId: 3,
    responsableFlotaId: 4,
    responsableMantenimientoFlotaId: 4,
    nombre: 'Flota Base',
    descripcion: 'Flota Base',
    estado: 3,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 31,
    padreId: 0,
    clienteId: 4,
    responsableFlotaId: 4,
    responsableMantenimientoFlotaId: 4,
    nombre: 'Flota Base',
    descripcion: 'Flota Base',
    estado: 3,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12168,
    padreId: 0,
    clienteId: 3,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'Xime1',
    descripcion: '',
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12169,
    padreId: 0,
    clienteId: 3,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'Xime2',
    descripcion: null,
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12174,
    padreId: 0,
    clienteId: 4,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'Ximemilla',
    descripcion: null,
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12175,
    padreId: 0,
    clienteId: 2,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'Que recibe',
    descripcion: null,
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12177,
    padreId: 0,
    clienteId: 4,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'FRecibirHAMD',
    descripcion: null,
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12178,
    padreId: 0,
    clienteId: 3,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'Pruebas 13/09',
    descripcion: null,
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
  {
    id: 12266,
    padreId: 0,
    clienteId: 2,
    responsableFlotaId: 0,
    responsableMantenimientoFlotaId: 0,
    nombre: 'demo1',
    descripcion: 'demo1',
    estado: 1,
    idCompartida: 0,
    estadoCompInfo: 0,
  },
];
