export default {
  vehiculos: [
    {
      id: 14152,
      unidad: 'KFHP19',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14153,
      unidad: 'KFHP24',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14154,
      unidad: 'KFHP17',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14157,
      unidad: 'JYVW75',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14158,
      unidad: 'JSCB20',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14160,
      unidad: 'JSCB21',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14162,
      unidad: 'JSCB19',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14163,
      unidad: 'JXPH35',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14165,
      unidad: 'JTVF38',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14166,
      unidad: 'JTVF33',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14167,
      unidad: 'KPWT47',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14168,
      unidad: 'KVJD89',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14169,
      unidad: 'KVJD91',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14170,
      unidad: 'KHJC11',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14172,
      unidad: 'JHKH59',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14173,
      unidad: 'JXRK66',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14174,
      unidad: 'JXRK64',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14175,
      unidad: 'KBSJ54',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14176,
      unidad: 'KHDV82',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14177,
      unidad: 'KHDS82',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14180,
      unidad: 'KHDS80',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14181,
      unidad: 'KHDV81',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14182,
      unidad: 'KHDS79',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14183,
      unidad: 'KJYY41',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14184,
      unidad: 'KJYY45',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14185,
      unidad: 'KHZL45',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14186,
      unidad: 'KHZV81',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14187,
      unidad: 'HYYR65',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14188,
      unidad: 'HYYR62',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14189,
      unidad: 'JRLH15',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14190,
      unidad: 'LBBB79',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14191,
      unidad: 'LBBB73',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14192,
      unidad: 'JKWR23',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14193,
      unidad: 'LBBB74',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14194,
      unidad: 'KWZZ84',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14196,
      unidad: 'LBBB72',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14197,
      unidad: 'JKWH52',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14198,
      unidad: 'GHRP19',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14199,
      unidad: 'HPBX27',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14200,
      unidad: 'HPBX29',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14201,
      unidad: 'HPBX30',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14202,
      unidad: 'JCCW39',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14203,
      unidad: 'HYZL39',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14204,
      unidad: 'HYZL40',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14205,
      unidad: 'HYZL33',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14206,
      unidad: 'HYZL29',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14207,
      unidad: 'HYZL31',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14208,
      unidad: 'HYZL42',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14209,
      unidad: 'HYZL32',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14210,
      unidad: 'HYZL37',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14211,
      unidad: 'HYZL41',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14212,
      unidad: 'HYZL34',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14213,
      unidad: 'HYZL36',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14214,
      unidad: 'HYZL35',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14215,
      unidad: 'HYZL38',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14216,
      unidad: 'JZBX51',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14218,
      unidad: 'JRLH16',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14219,
      unidad: 'JRLH17',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14221,
      unidad: 'JVBP55',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14222,
      unidad: 'JPKZ14',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14223,
      unidad: 'JRVH83',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14224,
      unidad: 'JRVH82',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14225,
      unidad: 'JRLH91',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14226,
      unidad: 'JDFP18',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14228,
      unidad: 'KBTV40',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14229,
      unidad: 'JSFD16',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14230,
      unidad: 'HWBH99',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 14231,
      unidad: 'LDGD17',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 17825,
      unidad: 'ER4567',
      etiquetas: [17],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 17845,
      unidad: 'EEEEE',
      etiquetas: [],
      flota: 7101,
      flotaNombre: 'Flota Base',
    },
    {
      id: 13593,
      unidad: 'KKSR29',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13594,
      unidad: 'KKSL98',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13615,
      unidad: 'JYWP39',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13721,
      unidad: 'JSBZ10',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13728,
      unidad: 'JSLS94',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13734,
      unidad: 'JDFW16',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13742,
      unidad: 'KKSL53',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13755,
      unidad: 'JTZZ87',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13765,
      unidad: 'KCSY78',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
    {
      id: 13776,
      unidad: 'KCTG87',
      etiquetas: [],
      flota: 13280,
      flotaNombre: 'VEHÍCULOS USADOS',
    },
  ],
  flotas: [
    { id: 7101, nombre: 'Flota Base', padre: null, nombrePadre: null },
    { id: 13280, nombre: 'VEHÍCULOS USADOS', padre: null, nombrePadre: null },
  ],
  etiquetas: [{ id: 17, nombre: 'wdwd' }],
};
