export default [
  {
    id: 450,
    clienteId: 4,
    nombre: 'Grupo de Zonas Base',
    descripcion: 'Grupo de Zonas Base',
    usuarioCreadorId: 4,
    usuarioModificacionId: null,
    fechaCreacion: '2019-09-11T15:47:17.798924',
    fechaModificacion: null,
    nombreCreador: null,
    nombreModificador: null,
    estado: 3,
    tipoLugarAlcance: 1,
    fechaModificacionTxt: null,
    estadoTxt: null,
    fechaCreacionTxt: null,
  },
  {
    id: 5054,
    clienteId: 4,
    nombre: 'Ximemilla',
    descripcion: 'mío mio de mi',
    usuarioCreadorId: 1013,
    usuarioModificacionId: null,
    fechaCreacion: '2019-09-12T15:02:58.5790569',
    fechaModificacion: null,
    nombreCreador: null,
    nombreModificador: null,
    estado: 1,
    tipoLugarAlcance: 1,
    fechaModificacionTxt: null,
    estadoTxt: null,
    fechaCreacionTxt: null,
  },
  {
    id: 5055,
    clienteId: null,
    nombre: 'GI Ximemilla',
    descripcion: null,
    usuarioCreadorId: 1013,
    usuarioModificacionId: null,
    fechaCreacion: '2019-09-12T15:05:00.5918317',
    fechaModificacion: null,
    nombreCreador: null,
    nombreModificador: null,
    estado: 1,
    tipoLugarAlcance: 2,
    fechaModificacionTxt: null,
    estadoTxt: null,
    fechaCreacionTxt: null,
  },
];
