name: 'Build and deploy to S3'

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing
    types: [ opened, synchronize ]

#oidc encima de oauth 2.0
permissions:
  id-token: write
  contents: read

jobs:
#  avoid_reduncy:
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Cancel Previous builds
#        uses: styfle/cancel-workflow-action@0.9.1
#        with:
#          access_token: ${{ github.token }}

  #  lint:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v3
  #        with:
  #          fetch-depth: 0
  #
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #          cache: 'npm'
  #
  #      - name: install
  #        run: npm ci --no-audit --no-fund
  #
  #      - name: Lint
  #        run: npm run eslint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci --no-audit --no-fund

      - name: compile dist
        run: npm run build -- --mode testing1

#      - uses: actions/upload-artifact@v2
#        if: ${{ github.event_name == 'push' }}
#        with:
#          name: dist
#          path: dist

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    needs: [ build ]

    steps:
      - name: "Finalizar"
        run: echo "Finaliza el proceso"
